; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; native is used for unit testing independent of hardware
[env:bitwise-test]
platform = native
test_framework = unity
test_build_src = false

test_filter = 
    test_native/test_bitwise


; the romi enviroment is the base env for examples
[env:romi]
platform = atmelavr
board = leonardo
framework = arduino
test_build_src = true

monitor_speed = 115200
test_framework = unity
test_filter = 
    test_leonardo

lib_deps =
    symlink:///home/binary/Desktop/RBE_2002/rangefinder-BinaryDoesCoding
    symlink:///home/binary/Desktop/RBE_2002/l-BinaryDoesCoding
    https://github.com/WPIRoboticsEngineering/Romi-32u4-Common-Defs
    https://github.com/WPIRoboticsEngineering/Romi-32u4-utilities
    https://github.com/gcl8a/event_timer


[env:battery_monitor]
extends = env:romi
build_src_filter =
    +<*>
    +<../examples/BatteryMonitor/src/*>

build_flags = 
    -D __BATTERY_DEBUG__

[env:pid_tuning]
extends = env:romi
build_src_filter =
    +<*>
    +<../examples/PID-tuning/src/*>

build_flags = 
    -D __MOTOR_DEBUG__
