; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; the romi enviroment is for unit testing on hardware
[env:romi]
platform = atmelavr
board = leonardo
framework = arduino

monitor_speed = 115200

; The symlinks below must be set to your local library directories
; The GitHub links are static libraries -- you will not edit those
lib_deps =
    symlink:///home/binary/Desktop/RBE_2002/l-BinaryDoesCoding
    symlink:///home/binary/Desktop/RBE_2002/rangefinder-BinaryDoesCoding
    https://github.com/WPIRoboticsEngineering/Romi-32u4-Common-Defs
    https://github.com/WPIRoboticsEngineering/Romi-32u4-utilities
    https://github.com/gcl8a/event_timer
    https://github.com/gcl8a/IRDecoder
    
; These can come in handy for debugging.
build_flags = 
;    -D __BATTERY_DEBUG__
;    -D __X_DEBUG__
;    -D __MOTOR_DEBUG__
;    -D __DIST_DEBUG__
;    -D __IMU_DEBUG__