; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; for unit testing independent of hardware
[env:median-filter-test]
platform = native
test_framework = unity
test_build_src = true
build_src_filter =
    +<*> -<HC-SR04> -<Rangefinder> -<Sharp-IR>
test_filter = 
    test_native/test_median_filter

[env:moving-avg-filter-test]
platform = native
test_framework = unity
test_build_src = true
build_src_filter =
    +<*> -<HC-SR04> -<Rangefinder> -<Sharp-IR>
test_filter = 
    test_native/test_moving_avg_filter

[env:lowpass-filter-test]
platform = native
test_framework = unity
test_build_src = true
build_src_filter =
    +<*> -<HC-SR04> -<Rangefinder> -<Sharp-IR>
test_filter = 
    test_native/test_lowpass_filter

[env:romi]
platform = atmelavr
board = a-star32U4
framework = arduino

lib_deps =
    https://github.com/WPIRoboticsEngineering/Romi-32u4-utilities

[env:HC-SR04-raw-demo]
extends = env:romi
build_src_filter = 
    +<*>
    +<../examples/HC-SR04-raw-demo>

[env:HC-SR04-filter-demo]
extends = env:romi
build_src_filter = 
    +<*>
    +<../examples/HC-SR04-filter-demo>
   
[env:Sharp-IR-demo]
extends = env:romi
build_src_filter = 
    +<*>
    +<../examples/Sharp-IR-demo>
   